use_frameworks!

target 'Updraft_Example' do
  pod 'Updraft', :path => '../'

  target 'Updraft_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
